# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: "running pipeline"
  displayName: 'Microservice Build & Validation'

  jobs:
    - job: "Jobtodemonstrate"
      displayName: "This is just a section to demonstrate this job"
      
      steps:
      - script: echo running my first pipeline! Hello world!
        displayName: 'Running first script'

      - script: |
          echo echo this is the finish of this pipeline.
        displayName: 'Running second script'
        

- stage: "deploying app"
  displayName: 'Microservice Build & Validation'

  jobs:
    - job: "Jobtodemonstrate"
      displayName: "This is just a section to demonstrate this job"
      
      steps:
      - script: echo running my first pipeline! Hello world!
        displayName: 'Running first script'

      - script: |
          echo echo this is the finish of this pipeline.
        displayName: 'Running second script'
        