# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:        
- stage: "runningSecondStageFromAPipe"
  displayName: 'Microservice Build & Validation'

  jobs:
    - job: "JobToDemonstrateSecondJob"
      displayName: "This is just a section to demonstrate this job"
      
      steps:
        - task: Gradle@2
          displayName: "Executing gradle command"
          inputs:
            workingDirectory: '../order'
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'build'
